#!/bin/bash
# Script to delete old log archives generated by spigot / paper
# The script will only remove files ending with .tar.gz
#
# Usage: purgeLogs.sh <path> <days>
# days: How many days since the file was last modified
# path: Path to the log directory to delete files from

USAGE="purgeLogs.sh <path> <days>";
if [ -z ${1+x} ];
 then 
 	echo "Missing argument path";
 	echo "Usage: $USAGE"
 	exit 1;
fi
if [ -z ${2+x} ];
 then 
 	echo "Missing argument days";
 	echo "Usage: $USAGE"
 	exit 1;
fi
find $1 -mtime +$2 -type f -iname '*.log.gz' -delete -print